### ISSUE TITLE
signin페이지 접속시 None값이 db에 추가됨

### ISSUE THREAD

**Issue by JunHo-YH** [rachel5004/ShareToDolistProject#18]
[{'id': 'test@naver.com', 'pwd': '1234'}, {'id': 'test2@naver.com', 'pwd': '5678'}, {'id': None, 'pwd': None}]
127.0.0.1 - - [21/Feb/2021 21:50:25] "POST /signin HTTP/1.1" 200 -
[{'id': 'test@naver.com', 'pwd': '1234'}, {'id': 'test2@naver.com', 'pwd': '5678'}, {'id': None, 'pwd': None}, {'id': 'aaa@a', 'pwd': 'aa'}]
127.0.0.1 - - [21/Feb/2021 21:50:31] "POST /signin HTTP/1.1" 200 -

None값이 안 들어가게 하는 좋은 방법이 있을까요?

**Comment by JunHo-YH** [comment]
none_delete 메서드로 처리했지만, 더 좋은 방법 있으시면 말씀해주세요 ~

**Comment by EungyuCho** [comment]
넣기전에 form validation을 해야할것 같습니당.
이건 서버에서 막는다기 보다 Client 측에서 email은 email 형식이 아니거나 비밀번호를 입력하지 않았을 때 button을 disable 시켜줘야 할거 같아요.

**Comment by im-gnar** [comment]
얘기햇지만 제일 처음 호출됐을때 초기값이 none이라 그런거라 저처럼 if not none 처리하거나 insert를 조건부로 빼도 될것같네요

**Comment by JunHo-YH** [comment]
두분 다 좋은 의견 감사합니다 ~!
form validation을 구현하기 전까지 insert메서드를 조건부로 빼두도록 하겠습니당
