### ISSUE TITLE
createRoom.js

### ISSUE THREAD

**Issue by im-gnar** [rachel5004/ShareToDolistProject#26]
#23 

- [x]  버튼 위치 : room list가 있을 경우 리스트 맨아래에 배치하면 리스트가 많을 때 문제가 될 것 같아서 search 근처쯤으로 생각하고있습니다
- [x] form에서 submit이 적용이 안 됨 : button을 disable하면 input도 submit이 안 됨
- [x] 파일을 수정할 때마다 main.html script에서 js?ver={int} 값을 올려줘야 반영이 됨...당장은 조금 번거로운 정도네요

**Comment by EungyuCho** [comment]
room list에는 room이 많을경우 스크롤이 가능합니다! (공유가 잘 안됐네요 죄송합니다)
버튼위치는 의논을 조금 더 해보고 결정합시다.

form 관련 작업은 제가 이어서 해보겠습니다!
