### ISSUE TITLE
get host for createroom method

### ISSUE THREAD

**Issue by im-gnar** [rachel5004/ShareToDolistProject#28]
#26  createroom 버튼은 디자인까지 해서 제 브랜치에 올려뒀습니다.
근데 room list가 #{host} {title} {/todolist/id} 형식이라 host값을 받아와야하는데

1. 현재 memberTB는 id(email), pwd 이니 @앞까지만 인덱싱해서 사용
2. 혹은 회원가입시 name 추가
 
중에 선택해야할 것 같습니다.
또 메인페이지에는 딱히 회원에 관한 데이터를 담고있지는 않아서... 추가를 시켜야하는데 이 부분은 생각을 좀 해봐야겟어요ㅜㅜ

**Comment by EungyuCho** [comment]
1번의 경우 아이디가 같고 뒤의 이메일이 다를경우엔 중복이 될거같아서 문제의 소지가 있어보이네요.
name을 추가하거나 host의 id(number)를 기준으로 가져와야 할 것 같습니다.
로그인이 되면 로그인한 회원의 name이나 id를 가지고 있어도 될것같네요.
데이터를 로그인할때 저장소(스토리지나 쿠키)에 넣어주거나 room create시에 response로 name이나 id를 받는 방법도 있겠네요.
