### ISSUE TITLE
Database

### ISSUE THREAD

**Issue by im-gnar** [rachel5004/ShareToDolistProject#3]
- [x] db 설치 및 설정
- [x] 필요한 테이블 및 컬럼 정의
- [x]  connect DB & send query (select)

DB는 SQLite
테이블은 user, roomlist는 필수
room 마다 따로 테이블을 두진않을텐데 어떻게 할지 고민해봅시다

user - id, pwd
roomlist - roomId, host(user.id), title
room?

++dokcer?

reference:
http://hleecaster.com/python-sqlite3/
http://pythonstudy.xyz/python/article/204-SQLite-%EC%82%AC%EC%9A%A9

**Comment by JunHo-YH** [comment]
넵! 열심히 자료 모아보겠습니다 ~!
