### ISSUE TITLE
Frontend

### ISSUE THREAD

**Issue by EungyuCho** [rachel5004/ShareToDolistProject#9]
**Common**
- [x] Apply Tailwind CSS
- [x] Apply Webpack
- [x] Docker-compose

**Design Reqired**
- [x] Main
- [x] Register
- [x] Login
- [x] ToDo

회원가입 성공은 바로 메인 페이지로 리다이렉트 하는게 낫지 않을까요??
우선 위 4페이지 작업 해보겠습니다 😄

**Comment by im-gnar** [comment]
성공했다는걸 알려주면 좋을 것 같긴 한데...그럼 페이지 말고 alter로라도 처리해보면 어떨까용

**Comment by EungyuCho** [comment]
성공했다는거 확인시켜주려면 페이지를 띄워주는게 맞겠네요!
